apiVersion: v1
kind: Service
metadata:
  name: chatops-test
  namespace: default
  labels:
    app: chatops-test
spec:
  selector:
    app: chatops-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 40080
  type: NodePort